name: Rust

defaults:
  run:
    working-directory: ./src-tauri
    
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: Swatinem/rust-cache@v2.7.3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
